run:
  timeout: 3m
  tests: true
  skip-dirs:
    - vendor

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - staticcheck
    - errcheck

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    checks:
      - all

